/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pi.apresentacao;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import pi.entidades.Documento;
import pi.negocios.DocumentoBO;
import pi.negocios.NegocioException;

/**
 *
 * @author Felipe Yuri Inoue
 */
public class TelaPrincipal extends javax.swing.JFrame {
int i=0;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
    private void showTela(String nome){
        CardLayout card = (CardLayout)conteiner.getLayout();
        card.show(conteiner, nome);
    }
    
    private void resetAta() {
        criaAta_campoTitulo.setText("");
        criaAta_campoTitulo.setText("");
        criaAta_campoLocal.setText("");
        criaAta_campoData.setText("");
        criaAta_campoHorario.setText("");
        criaAta_campoAssunto.setText("");
        criaAta_campoApont.setText("");
        criaAta_campoEncamin.setText("");
        criaAta_campoDecisoes.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conteiner = new javax.swing.JPanel();
        painelInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        painelCriar = new javax.swing.JPanel();
        labelMenuItemCriar = new javax.swing.JLabel();
        painelBotoes = new javax.swing.JPanel();
        botaoConfirmar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        painelTitulo = new javax.swing.JPanel();
        criaAta_labelTitulo = new javax.swing.JLabel();
        criaAta_campoTitulo = new javax.swing.JTextField();
        painelCombos = new javax.swing.JPanel();
        labelClassificacao = new javax.swing.JLabel();
        comboClassificacao = new javax.swing.JComboBox<>();
        labelModelo = new javax.swing.JLabel();
        comboModelo = new javax.swing.JComboBox<>();
        painelRolagemAta = new javax.swing.JScrollPane();
        painelCriaAta = new javax.swing.JPanel();
        criaAta_painelTitulo = new javax.swing.JPanel();
        criaAta_labelCriar = new javax.swing.JLabel();
        criaAta_painelDados = new javax.swing.JPanel();
        criaAta_painelDadosDaAta = new javax.swing.JPanel();
        criaAta_labelLocal = new javax.swing.JLabel();
        criaAta_campoLocal = new javax.swing.JTextField();
        criaAta_labelData = new javax.swing.JLabel();
        criaAta_campoData = new javax.swing.JTextField();
        criaAta_labelHorario = new javax.swing.JLabel();
        criaAta_campoHorario = new javax.swing.JTextField();
        criaAta_labelTipo = new javax.swing.JLabel();
        criaAta_campoTipo = new javax.swing.JComboBox<>();
        criaAta_labelClassif = new javax.swing.JLabel();
        criaAta_campoClassif = new javax.swing.JComboBox<>();
        criaAta_labelEncamin = new javax.swing.JLabel();
        criaAta_campoEncamin = new javax.swing.JTextField();
        criaAta_painelConvidados = new javax.swing.JPanel();
        criaAta_rolagemConvidados = new javax.swing.JScrollPane();
        criaAta_tabelaConvidados = new javax.swing.JTable();
        criaAta_painelAssunto = new javax.swing.JPanel();
        criaAta_rolagemAssunto = new javax.swing.JScrollPane();
        criaAta_campoAssunto = new javax.swing.JTextArea();
        criaAta_painelApont = new javax.swing.JPanel();
        criaAta_rolagemApont = new javax.swing.JScrollPane();
        criaAta_campoApont = new javax.swing.JTextArea();
        criaAta_painelDecisoes = new javax.swing.JPanel();
        criaAta_rolagemDecisoes = new javax.swing.JScrollPane();
        criaAta_campoDecisoes = new javax.swing.JTextArea();
        criaAta_painelBotoes = new javax.swing.JPanel();
        botaoSair = new javax.swing.JButton();
        botaoEnviar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        menuItemInicio = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemSair = new javax.swing.JMenuItem();
        menuDocumento = new javax.swing.JMenu();
        menuItemCriar = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        itemMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Atas e Atos");
        setMinimumSize(new java.awt.Dimension(900, 700));
        setPreferredSize(new java.awt.Dimension(900, 700));

        conteiner.setLayout(new java.awt.CardLayout());

        painelInicio.setMaximumSize(new java.awt.Dimension(800, 600));
        painelInicio.setMinimumSize(new java.awt.Dimension(800, 600));
        painelInicio.setName(""); // NOI18N
        painelInicio.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Início");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sistema de Atos e Atas");

        javax.swing.GroupLayout painelInicioLayout = new javax.swing.GroupLayout(painelInicio);
        painelInicio.setLayout(painelInicioLayout);
        painelInicioLayout.setHorizontalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelInicioLayout.setVerticalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInicioLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        conteiner.add(painelInicio, "card2");

        painelCriar.setMaximumSize(new java.awt.Dimension(800, 600));
        painelCriar.setMinimumSize(new java.awt.Dimension(800, 600));
        painelCriar.setPreferredSize(new java.awt.Dimension(800, 600));

        labelMenuItemCriar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelMenuItemCriar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenuItemCriar.setText("Criar Documento");

        botaoConfirmar.setText("Confirmar");
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });
        painelBotoes.add(botaoConfirmar);

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        painelBotoes.add(botaoCancelar);

        criaAta_labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        criaAta_labelTitulo.setText("Título: ");
        painelTitulo.add(criaAta_labelTitulo);

        criaAta_campoTitulo.setColumns(40);
        painelTitulo.add(criaAta_campoTitulo);

        labelClassificacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelClassificacao.setText("Classificação:");
        painelCombos.add(labelClassificacao);

        comboClassificacao.setMaximumRowCount(3);
        comboClassificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Confidencial", "Restrito", "Livre" }));
        comboClassificacao.setMinimumSize(new java.awt.Dimension(83, 30));
        comboClassificacao.setPreferredSize(new java.awt.Dimension(120, 30));
        painelCombos.add(comboClassificacao);

        labelModelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelModelo.setText("Modelo: ");
        painelCombos.add(labelModelo);

        comboModelo.setMaximumRowCount(2);
        comboModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ato", "Ata" }));
        comboModelo.setMinimumSize(new java.awt.Dimension(42, 30));
        comboModelo.setPreferredSize(new java.awt.Dimension(110, 30));
        painelCombos.add(comboModelo);

        javax.swing.GroupLayout painelCriarLayout = new javax.swing.GroupLayout(painelCriar);
        painelCriar.setLayout(painelCriarLayout);
        painelCriarLayout.setHorizontalGroup(
            painelCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMenuItemCriar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelCombos, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelCriarLayout.setVerticalGroup(
            painelCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCriarLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(labelMenuItemCriar)
                .addGap(27, 27, 27)
                .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCombos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        conteiner.add(painelCriar, "card3");

        painelRolagemAta.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        painelRolagemAta.setMinimumSize(new java.awt.Dimension(700, 500));
        painelRolagemAta.setPreferredSize(new java.awt.Dimension(700, 600));
        painelRolagemAta.setRequestFocusEnabled(false);

        painelCriaAta.setLayout(new javax.swing.BoxLayout(painelCriaAta, javax.swing.BoxLayout.Y_AXIS));

        criaAta_labelCriar.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        criaAta_labelCriar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        criaAta_labelCriar.setText("Criando Documento - Ata");
        criaAta_labelCriar.setToolTipText("");

        javax.swing.GroupLayout criaAta_painelTituloLayout = new javax.swing.GroupLayout(criaAta_painelTitulo);
        criaAta_painelTitulo.setLayout(criaAta_painelTituloLayout);
        criaAta_painelTituloLayout.setHorizontalGroup(
            criaAta_painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
            .addGroup(criaAta_painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(criaAta_painelTituloLayout.createSequentialGroup()
                    .addGap(0, 149, Short.MAX_VALUE)
                    .addComponent(criaAta_labelCriar)
                    .addGap(0, 150, Short.MAX_VALUE)))
        );
        criaAta_painelTituloLayout.setVerticalGroup(
            criaAta_painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
            .addGroup(criaAta_painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(criaAta_painelTituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(criaAta_labelCriar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        painelCriaAta.add(criaAta_painelTitulo);

        criaAta_painelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Ata"));

        criaAta_labelLocal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        criaAta_labelLocal.setText("Local: ");

        criaAta_labelData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        criaAta_labelData.setText("Data: ");

        criaAta_labelHorario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        criaAta_labelHorario.setText("Horário: ");

        criaAta_labelTipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        criaAta_labelTipo.setText("Tipo: ");

        criaAta_campoTipo.setMaximumRowCount(3);
        criaAta_campoTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reunião", "Assembléia", "Convenção" }));

        criaAta_labelClassif.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        criaAta_labelClassif.setText("Classificação: ");

        criaAta_campoClassif.setMaximumRowCount(2);
        criaAta_campoClassif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pública", "Privada" }));

        criaAta_labelEncamin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        criaAta_labelEncamin.setText("Encaminhamento: ");

        javax.swing.GroupLayout criaAta_painelDadosDaAtaLayout = new javax.swing.GroupLayout(criaAta_painelDadosDaAta);
        criaAta_painelDadosDaAta.setLayout(criaAta_painelDadosDaAtaLayout);
        criaAta_painelDadosDaAtaLayout.setHorizontalGroup(
            criaAta_painelDadosDaAtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
            .addGroup(criaAta_painelDadosDaAtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(criaAta_painelDadosDaAtaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(criaAta_painelDadosDaAtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(criaAta_labelHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(criaAta_labelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(criaAta_labelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(criaAta_labelClassif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(criaAta_labelEncamin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(criaAta_labelLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(criaAta_painelDadosDaAtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(criaAta_campoLocal)
                        .addComponent(criaAta_campoData)
                        .addComponent(criaAta_campoClassif, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(criaAta_campoTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(criaAta_campoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(criaAta_campoEncamin, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
        criaAta_painelDadosDaAtaLayout.setVerticalGroup(
            criaAta_painelDadosDaAtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
            .addGroup(criaAta_painelDadosDaAtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(criaAta_painelDadosDaAtaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(criaAta_painelDadosDaAtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(criaAta_campoLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(criaAta_labelLocal))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(criaAta_painelDadosDaAtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(criaAta_labelData)
                        .addComponent(criaAta_campoData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(criaAta_painelDadosDaAtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(criaAta_labelHorario)
                        .addComponent(criaAta_campoHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(criaAta_painelDadosDaAtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(criaAta_labelTipo)
                        .addComponent(criaAta_campoTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(criaAta_painelDadosDaAtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(criaAta_campoClassif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(criaAta_labelClassif))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(criaAta_painelDadosDaAtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(criaAta_labelEncamin)
                        .addComponent(criaAta_campoEncamin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        criaAta_painelDados.add(criaAta_painelDadosDaAta);

        painelCriaAta.add(criaAta_painelDados);

        criaAta_painelConvidados.setBorder(javax.swing.BorderFactory.createTitledBorder("Convidados"));

        criaAta_rolagemConvidados.setPreferredSize(new java.awt.Dimension(500, 100));

        criaAta_tabelaConvidados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Presente?"
            }
        ));
        criaAta_rolagemConvidados.setViewportView(criaAta_tabelaConvidados);

        criaAta_painelConvidados.add(criaAta_rolagemConvidados);

        painelCriaAta.add(criaAta_painelConvidados);

        criaAta_painelAssunto.setBorder(javax.swing.BorderFactory.createTitledBorder("Assuntos"));

        criaAta_rolagemAssunto.setMinimumSize(new java.awt.Dimension(500, 200));
        criaAta_rolagemAssunto.setPreferredSize(new java.awt.Dimension(500, 200));

        criaAta_campoAssunto.setColumns(20);
        criaAta_campoAssunto.setRows(5);
        criaAta_campoAssunto.setPreferredSize(null);
        criaAta_rolagemAssunto.setViewportView(criaAta_campoAssunto);

        criaAta_painelAssunto.add(criaAta_rolagemAssunto);

        painelCriaAta.add(criaAta_painelAssunto);

        criaAta_painelApont.setBorder(javax.swing.BorderFactory.createTitledBorder("Apontamentos"));

        criaAta_rolagemApont.setMinimumSize(new java.awt.Dimension(500, 200));
        criaAta_rolagemApont.setPreferredSize(new java.awt.Dimension(500, 200));

        criaAta_campoApont.setColumns(20);
        criaAta_campoApont.setRows(5);
        criaAta_campoApont.setPreferredSize(null);
        criaAta_rolagemApont.setViewportView(criaAta_campoApont);

        criaAta_painelApont.add(criaAta_rolagemApont);

        painelCriaAta.add(criaAta_painelApont);

        criaAta_painelDecisoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Decisões"));

        criaAta_rolagemDecisoes.setMinimumSize(new java.awt.Dimension(500, 200));
        criaAta_rolagemDecisoes.setPreferredSize(new java.awt.Dimension(500, 200));

        criaAta_campoDecisoes.setColumns(20);
        criaAta_campoDecisoes.setRows(5);
        criaAta_campoDecisoes.setPreferredSize(null);
        criaAta_rolagemDecisoes.setViewportView(criaAta_campoDecisoes);

        criaAta_painelDecisoes.add(criaAta_rolagemDecisoes);

        painelCriaAta.add(criaAta_painelDecisoes);

        botaoSair.setText("Cancelar");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });
        criaAta_painelBotoes.add(botaoSair);

        botaoEnviar.setText("Enviar");
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });
        criaAta_painelBotoes.add(botaoEnviar);

        painelCriaAta.add(criaAta_painelBotoes);

        painelRolagemAta.setViewportView(painelCriaAta);

        conteiner.add(painelRolagemAta, "card4");

        menuMenu.setText("Menu");

        menuItemInicio.setText("Início");
        menuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInicioActionPerformed(evt);
            }
        });
        menuMenu.add(menuItemInicio);
        menuMenu.add(jSeparator1);

        menuItemSair.setMnemonic('s');
        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuMenu.add(menuItemSair);

        jMenuBar1.add(menuMenu);

        menuDocumento.setText("Documento");

        menuItemCriar.setText("Criar Documento");
        menuItemCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCriarActionPerformed(evt);
            }
        });
        menuDocumento.add(menuItemCriar);

        jMenuBar1.add(menuDocumento);

        menuSobre.setText("Sobre...");

        itemMenuSobre.setText("Grupo 7");
        itemMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSobreActionPerformed(evt);
            }
        });
        menuSobre.add(itemMenuSobre);

        jMenuBar1.add(menuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(conteiner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(conteiner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        TelaLogin janelaLogin = new TelaLogin();
        this.setVisible(false);
        janelaLogin.setVisible(true);
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void itemMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSobreActionPerformed
        TelaSobre janelaSobre = new TelaSobre(this, true);
        janelaSobre.setVisible(true);
        janelaSobre.setLocationRelativeTo(null);
    }//GEN-LAST:event_itemMenuSobreActionPerformed

    private void menuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInicioActionPerformed
        showTela("card2");
    }//GEN-LAST:event_menuItemInicioActionPerformed

    private void menuItemCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCriarActionPerformed
        showTela("card3");
    }//GEN-LAST:event_menuItemCriarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        showTela("card2");
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed
        Documento doc = new Documento();
        doc.setTitulo(criaAta_campoTitulo.getText());
        doc.setClassificacao(comboClassificacao.getSelectedIndex());
        doc.setModelo(comboModelo.getSelectedItem().toString());

        System.out.println(comboClassificacao.getSelectedIndex());

        DocumentoBO bo = new DocumentoBO();

        try {
            bo.validarCriacao(doc);
            if(comboModelo.getSelectedItem().toString() == "Ato") {
                showTela("card4");
            }
            else {
                showTela("card4");
            }
        } catch (NegocioException ex) {
            System.out.println("Erro ao criar documento. ["+ex+"]");
        }
    }//GEN-LAST:event_botaoConfirmarActionPerformed

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
        Documento doc = new Documento();
        doc.setTitulo(criaAta_campoTitulo.getText());
        doc.setClassificacao(comboClassificacao.getSelectedIndex());
        doc.setModelo(comboModelo.getSelectedItem().toString());
        doc.setLocal(criaAta_campoLocal.getText());
        doc.setData(criaAta_campoData.getText());
        doc.setHorario(criaAta_campoHorario.getText());
        doc.setAssunto(criaAta_campoAssunto.getText());
        doc.setApontamento(criaAta_campoApont.getText());
        doc.setEncaminhamento(criaAta_campoEncamin.getText());

        DocumentoBO bo = new DocumentoBO();
        try {
            bo.inserir(doc);
            JOptionPane.showMessageDialog(this, "Criado com Sucesso!");
            resetAta();
            showTela("card3");
        } catch (NegocioException ex) {
            System.out.println("Erro ao criar documento completo. ["+ex+"]");
        }
    }//GEN-LAST:event_botaoEnviarActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?",
            "Confirmação",JOptionPane.YES_NO_OPTION);

        if(opcao == JOptionPane.YES_OPTION){
            showTela("card3");
        }
    }//GEN-LAST:event_botaoSairActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JComboBox<String> comboClassificacao;
    private javax.swing.JComboBox<String> comboModelo;
    private javax.swing.JPanel conteiner;
    private javax.swing.JTextArea criaAta_campoApont;
    private javax.swing.JTextArea criaAta_campoAssunto;
    private javax.swing.JComboBox<String> criaAta_campoClassif;
    private javax.swing.JTextField criaAta_campoData;
    private javax.swing.JTextArea criaAta_campoDecisoes;
    private javax.swing.JTextField criaAta_campoEncamin;
    private javax.swing.JTextField criaAta_campoHorario;
    private javax.swing.JTextField criaAta_campoLocal;
    private javax.swing.JComboBox<String> criaAta_campoTipo;
    private javax.swing.JTextField criaAta_campoTitulo;
    private javax.swing.JLabel criaAta_labelClassif;
    private javax.swing.JLabel criaAta_labelCriar;
    private javax.swing.JLabel criaAta_labelData;
    private javax.swing.JLabel criaAta_labelEncamin;
    private javax.swing.JLabel criaAta_labelHorario;
    private javax.swing.JLabel criaAta_labelLocal;
    private javax.swing.JLabel criaAta_labelTipo;
    private javax.swing.JLabel criaAta_labelTitulo;
    private javax.swing.JPanel criaAta_painelApont;
    private javax.swing.JPanel criaAta_painelAssunto;
    private javax.swing.JPanel criaAta_painelBotoes;
    private javax.swing.JPanel criaAta_painelConvidados;
    private javax.swing.JPanel criaAta_painelDados;
    private javax.swing.JPanel criaAta_painelDadosDaAta;
    private javax.swing.JPanel criaAta_painelDecisoes;
    private javax.swing.JPanel criaAta_painelTitulo;
    private javax.swing.JScrollPane criaAta_rolagemApont;
    private javax.swing.JScrollPane criaAta_rolagemAssunto;
    private javax.swing.JScrollPane criaAta_rolagemConvidados;
    private javax.swing.JScrollPane criaAta_rolagemDecisoes;
    private javax.swing.JTable criaAta_tabelaConvidados;
    private javax.swing.JMenuItem itemMenuSobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel labelClassificacao;
    private javax.swing.JLabel labelMenuItemCriar;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JMenu menuDocumento;
    private javax.swing.JMenuItem menuItemCriar;
    private javax.swing.JMenuItem menuItemInicio;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelCombos;
    private javax.swing.JPanel painelCriaAta;
    private javax.swing.JPanel painelCriar;
    private javax.swing.JPanel painelInicio;
    private javax.swing.JScrollPane painelRolagemAta;
    private javax.swing.JPanel painelTitulo;
    // End of variables declaration//GEN-END:variables
}
