/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pi.apresentacao;

import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pi.entidades.Documento;
import pi.negocios.DocumentoBO;
import pi.negocios.NegocioException;
import pi.dados.DocumentoDAO;
import pi.dados.DadosException;

/**
 *
 * @author Felipe Yuri Inoue
 */
public class TelaPrincipal extends javax.swing.JFrame {
int i=0;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
    private void showTela(String nome){
        CardLayout card = (CardLayout)conteiner.getLayout();
        card.show(conteiner, nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conteiner = new javax.swing.JPanel();
        painelInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        painelCriar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        campoTitulo = new javax.swing.JTextField();
        labelClassificacao = new javax.swing.JLabel();
        comboClassificacao = new javax.swing.JComboBox<>();
        labelModelo = new javax.swing.JLabel();
        comboModelo = new javax.swing.JComboBox<>();
        botaoConfirmar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        painelRolagemAta = new javax.swing.JScrollPane();
        painelPrincipal = new javax.swing.JPanel();
        painelDados2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        campoLocal2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        campoData2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        campoHora2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        campoEncamin2 = new javax.swing.JTextField();
        painelConvidados = new javax.swing.JPanel();
        rolagemTabela = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        painelAssunto = new javax.swing.JPanel();
        rolagemAssuntos = new javax.swing.JScrollPane();
        campoAssunto = new javax.swing.JTextArea();
        painelApontamen = new javax.swing.JPanel();
        rolagemApontamen = new javax.swing.JScrollPane();
        campoApontamen = new javax.swing.JTextArea();
        painelDecisoes = new javax.swing.JPanel();
        rolagemDecisoes = new javax.swing.JScrollPane();
        campoDecisoes = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        botaoEnviar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        painelRolagemAto = new javax.swing.JScrollPane();
        painelPrincipal2 = new javax.swing.JPanel();
        painelDados3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        campoLocal3 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        campoData3 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        campoHora3 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        campoEncamin3 = new javax.swing.JTextField();
        painelAprovadores = new javax.swing.JPanel();
        rolagemTabela2 = new javax.swing.JScrollPane();
        tabelaAprovador = new javax.swing.JTable();
        painelTexto = new javax.swing.JPanel();
        rolagemTexto = new javax.swing.JScrollPane();
        campoTexto = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        botaoEnviarAto = new javax.swing.JButton();
        botaoCancelarAto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        menuItemInicio = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemSair = new javax.swing.JMenuItem();
        menuDocumento = new javax.swing.JMenu();
        menuItemCriar = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        itemMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Atas e Atos");

        conteiner.setLayout(new java.awt.CardLayout());

        painelInicio.setMaximumSize(new java.awt.Dimension(800, 600));
        painelInicio.setMinimumSize(new java.awt.Dimension(800, 600));
        painelInicio.setName(""); // NOI18N
        painelInicio.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Início");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sistema de Atos e Atas");

        javax.swing.GroupLayout painelInicioLayout = new javax.swing.GroupLayout(painelInicio);
        painelInicio.setLayout(painelInicioLayout);
        painelInicioLayout.setHorizontalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelInicioLayout.setVerticalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInicioLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        conteiner.add(painelInicio, "card2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Criar Documento");

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTitulo.setText("Título: ");

        labelClassificacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelClassificacao.setText("Classificação:");

        comboClassificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Confidencial", "Restrito", "Livre" }));

        labelModelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelModelo.setText("Modelo: ");

        comboModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ato", "Ata" }));

        botaoConfirmar.setText("Confirmar");
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCriarLayout = new javax.swing.GroupLayout(painelCriar);
        painelCriar.setLayout(painelCriarLayout);
        painelCriarLayout.setHorizontalGroup(
            painelCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelCriarLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(painelCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCriarLayout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCriarLayout.createSequentialGroup()
                        .addGroup(painelCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelCriarLayout.createSequentialGroup()
                                .addComponent(botaoCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoConfirmar))
                            .addGroup(painelCriarLayout.createSequentialGroup()
                                .addComponent(labelClassificacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(labelModelo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        painelCriarLayout.setVerticalGroup(
            painelCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCriarLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(painelCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo)
                    .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClassificacao)
                    .addComponent(comboClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelModelo)
                    .addComponent(comboModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(painelCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConfirmar)
                    .addComponent(botaoCancelar))
                .addContainerGap(352, Short.MAX_VALUE))
        );

        conteiner.add(painelCriar, "card3");

        painelDados2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Ata"));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Local: ");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Data: ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Horário: ");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Tipo: ");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------", "Reunião", "Assembléia", "Convenção" }));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Classificação: ");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------", "Pública", "Privada", " " }));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Encaminhamento: ");

        javax.swing.GroupLayout painelDados2Layout = new javax.swing.GroupLayout(painelDados2);
        painelDados2.setLayout(painelDados2Layout);
        painelDados2Layout.setHorizontalGroup(
            painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDados2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel22)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoData2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEncamin2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(campoHora2)
                    .addComponent(campoLocal2))
                .addGap(150, 150, 150))
        );
        painelDados2Layout.setVerticalGroup(
            painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDados2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(campoLocal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(campoData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(campoHora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(campoEncamin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        painelConvidados.setBorder(javax.swing.BorderFactory.createTitledBorder("Convidados"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Presente?"
            }
        ));
        rolagemTabela.setViewportView(jTable1);

        javax.swing.GroupLayout painelConvidadosLayout = new javax.swing.GroupLayout(painelConvidados);
        painelConvidados.setLayout(painelConvidadosLayout);
        painelConvidadosLayout.setHorizontalGroup(
            painelConvidadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConvidadosLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(rolagemTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelConvidadosLayout.setVerticalGroup(
            painelConvidadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConvidadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rolagemTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelAssunto.setBorder(javax.swing.BorderFactory.createTitledBorder("Assuntos"));

        campoAssunto.setColumns(20);
        campoAssunto.setRows(5);
        campoAssunto.setPreferredSize(null);
        rolagemAssuntos.setViewportView(campoAssunto);

        javax.swing.GroupLayout painelAssuntoLayout = new javax.swing.GroupLayout(painelAssunto);
        painelAssunto.setLayout(painelAssuntoLayout);
        painelAssuntoLayout.setHorizontalGroup(
            painelAssuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAssuntoLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(rolagemAssuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        painelAssuntoLayout.setVerticalGroup(
            painelAssuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAssuntoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rolagemAssuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        painelApontamen.setBorder(javax.swing.BorderFactory.createTitledBorder("Apontamentos"));

        campoApontamen.setColumns(20);
        campoApontamen.setRows(5);
        rolagemApontamen.setViewportView(campoApontamen);

        javax.swing.GroupLayout painelApontamenLayout = new javax.swing.GroupLayout(painelApontamen);
        painelApontamen.setLayout(painelApontamenLayout);
        painelApontamenLayout.setHorizontalGroup(
            painelApontamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelApontamenLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(rolagemApontamen, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelApontamenLayout.setVerticalGroup(
            painelApontamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelApontamenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rolagemApontamen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        painelDecisoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Decisões"));

        campoDecisoes.setColumns(20);
        campoDecisoes.setRows(5);
        rolagemDecisoes.setViewportView(campoDecisoes);

        javax.swing.GroupLayout painelDecisoesLayout = new javax.swing.GroupLayout(painelDecisoes);
        painelDecisoes.setLayout(painelDecisoesLayout);
        painelDecisoesLayout.setHorizontalGroup(
            painelDecisoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDecisoesLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(rolagemDecisoes, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelDecisoesLayout.setVerticalGroup(
            painelDecisoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDecisoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rolagemDecisoes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Criando Documento - Ata");

        botaoEnviar.setText("Enviar");
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });

        botaoSair.setText("Cancelar");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(painelConvidados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelAssunto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelApontamen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelDecisoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelDados2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel11))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(botaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelDados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelConvidados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelApontamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDecisoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEnviar)
                    .addComponent(botaoSair))
                .addGap(22, 22, 22))
        );

        painelRolagemAta.setViewportView(painelPrincipal);

        conteiner.add(painelRolagemAta, "card4");

        painelDados3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Ato"));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Local: ");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Data: ");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Horário: ");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Tipo: ");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------", "Reunião", "Assembléia", "Convenção" }));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("Classificação: ");

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------", "Pública", "Privada", " " }));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("Encaminhamento: ");

        javax.swing.GroupLayout painelDados3Layout = new javax.swing.GroupLayout(painelDados3);
        painelDados3.setLayout(painelDados3Layout);
        painelDados3Layout.setHorizontalGroup(
            painelDados3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDados3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelDados3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel23)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDados3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoData3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEncamin3)
                    .addComponent(campoHora3)
                    .addComponent(campoLocal3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );
        painelDados3Layout.setVerticalGroup(
            painelDados3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDados3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(painelDados3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(campoLocal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDados3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(campoData3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDados3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(campoHora3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDados3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDados3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDados3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(campoEncamin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        painelAprovadores.setBorder(javax.swing.BorderFactory.createTitledBorder("Aprovadores"));

        tabelaAprovador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nível de Aprovação", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rolagemTabela2.setViewportView(tabelaAprovador);

        javax.swing.GroupLayout painelAprovadoresLayout = new javax.swing.GroupLayout(painelAprovadores);
        painelAprovadores.setLayout(painelAprovadoresLayout);
        painelAprovadoresLayout.setHorizontalGroup(
            painelAprovadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAprovadoresLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(rolagemTabela2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelAprovadoresLayout.setVerticalGroup(
            painelAprovadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAprovadoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rolagemTabela2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );

        painelTexto.setBorder(javax.swing.BorderFactory.createTitledBorder("Texto"));

        campoTexto.setColumns(20);
        campoTexto.setRows(5);
        rolagemTexto.setViewportView(campoTexto);

        javax.swing.GroupLayout painelTextoLayout = new javax.swing.GroupLayout(painelTexto);
        painelTexto.setLayout(painelTextoLayout);
        painelTextoLayout.setHorizontalGroup(
            painelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTextoLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(rolagemTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelTextoLayout.setVerticalGroup(
            painelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rolagemTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setText("Criando Documento - Ato");

        botaoEnviarAto.setText("Enviar");
        botaoEnviarAto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarAtoActionPerformed(evt);
            }
        });

        botaoCancelarAto.setText("Cancelar");
        botaoCancelarAto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarAtoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipal2Layout = new javax.swing.GroupLayout(painelPrincipal2);
        painelPrincipal2.setLayout(painelPrincipal2Layout);
        painelPrincipal2Layout.setHorizontalGroup(
            painelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipal2Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(188, 188, 188))
            .addGroup(painelPrincipal2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipal2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoCancelarAto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(botaoEnviarAto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257))
                    .addComponent(painelDados3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelAprovadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelPrincipal2Layout.setVerticalGroup(
            painelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipal2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelDados3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelAprovadores, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(painelPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEnviarAto)
                    .addComponent(botaoCancelarAto))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        painelRolagemAto.setViewportView(painelPrincipal2);

        conteiner.add(painelRolagemAto, "card5");

        menuMenu.setText("Menu");

        menuItemInicio.setText("Início");
        menuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInicioActionPerformed(evt);
            }
        });
        menuMenu.add(menuItemInicio);
        menuMenu.add(jSeparator1);

        menuItemSair.setMnemonic('s');
        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuMenu.add(menuItemSair);

        jMenuBar1.add(menuMenu);

        menuDocumento.setText("Documento");

        menuItemCriar.setText("Criar Documento");
        menuItemCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCriarActionPerformed(evt);
            }
        });
        menuDocumento.add(menuItemCriar);

        jMenuBar1.add(menuDocumento);

        menuSobre.setText("Sobre...");

        itemMenuSobre.setText("Grupo 7");
        itemMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSobreActionPerformed(evt);
            }
        });
        menuSobre.add(itemMenuSobre);

        jMenuBar1.add(menuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(conteiner, javax.swing.GroupLayout.PREFERRED_SIZE, 784, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(conteiner, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        TelaLogin janelaLogin = new TelaLogin();
        this.setVisible(false);
        janelaLogin.setVisible(true);
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void itemMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSobreActionPerformed
        TelaSobre janelaSobre = new TelaSobre(this, true);
        janelaSobre.setVisible(true);
        janelaSobre.setLocationRelativeTo(null);
    }//GEN-LAST:event_itemMenuSobreActionPerformed

    private void menuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInicioActionPerformed
        showTela("card2");
    }//GEN-LAST:event_menuItemInicioActionPerformed

    private void menuItemCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCriarActionPerformed
        showTela("card3");
    }//GEN-LAST:event_menuItemCriarActionPerformed

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed
        Documento doc = new Documento();
        doc.setTitulo(campoTitulo.getText());
        doc.setClassificacao(comboClassificacao.getSelectedIndex());
        doc.setModelo(comboModelo.getSelectedItem().toString());
        
        System.out.println(comboClassificacao.getSelectedIndex());
        
        DocumentoBO bo = new DocumentoBO();
        
        try {
            bo.validarCriacao(doc);
            if(comboModelo.getSelectedItem().toString() == "Ato") {
                showTela("card5");
            }
            else {
                showTela("card4");    
            }
        } catch (NegocioException ex) {
            System.out.println("Erro ao criar documento. ["+ex+"]");
        }
    }//GEN-LAST:event_botaoConfirmarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        showTela("card2");
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?",
            "Confirmação",JOptionPane.YES_NO_OPTION);

        if(opcao == JOptionPane.YES_OPTION){
            showTela("card3");
        }
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
        Documento doc = new Documento();
        doc.setTitulo(campoTitulo.getText());
        doc.setLocal(campoLocal2.getText());
        doc.setData(campoData2.getText());
        doc.setHorario(campoHora2.getText());
        doc.setAssunto(campoAssunto.getText());
        doc.setClassificacao(comboModelo.getSelectedIndex());
        doc.setEncaminhamento(campoEncamin2.getText());
        
        DocumentoBO bo = new DocumentoBO();
        try {
            bo.inserir(doc);
            JOptionPane.showMessageDialog(this, "Criado com Sucesso!");
        } catch (NegocioException ex) {
            System.out.println("Erro ao criar documento completo. ["+ex+"]");
        }
    }//GEN-LAST:event_botaoEnviarActionPerformed

    private void botaoEnviarAtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarAtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEnviarAtoActionPerformed

    private void botaoCancelarAtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarAtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCancelarAtoActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoCancelarAto;
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JButton botaoEnviarAto;
    private javax.swing.JButton botaoSair;
    private javax.swing.JTextArea campoApontamen;
    private javax.swing.JTextArea campoAssunto;
    private javax.swing.JTextField campoData2;
    private javax.swing.JTextField campoData3;
    private javax.swing.JTextArea campoDecisoes;
    private javax.swing.JTextField campoEncamin2;
    private javax.swing.JTextField campoEncamin3;
    private javax.swing.JTextField campoHora2;
    private javax.swing.JTextField campoHora3;
    private javax.swing.JTextField campoLocal2;
    private javax.swing.JTextField campoLocal3;
    private javax.swing.JTextArea campoTexto;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JComboBox<String> comboClassificacao;
    private javax.swing.JComboBox<String> comboModelo;
    private javax.swing.JPanel conteiner;
    private javax.swing.JMenuItem itemMenuSobre;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelClassificacao;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JMenu menuDocumento;
    private javax.swing.JMenuItem menuItemCriar;
    private javax.swing.JMenuItem menuItemInicio;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JPanel painelApontamen;
    private javax.swing.JPanel painelAprovadores;
    private javax.swing.JPanel painelAssunto;
    private javax.swing.JPanel painelConvidados;
    private javax.swing.JPanel painelCriar;
    private javax.swing.JPanel painelDados2;
    private javax.swing.JPanel painelDados3;
    private javax.swing.JPanel painelDecisoes;
    private javax.swing.JPanel painelInicio;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelPrincipal2;
    private javax.swing.JScrollPane painelRolagemAta;
    private javax.swing.JScrollPane painelRolagemAto;
    private javax.swing.JPanel painelTexto;
    private javax.swing.JScrollPane rolagemApontamen;
    private javax.swing.JScrollPane rolagemAssuntos;
    private javax.swing.JScrollPane rolagemDecisoes;
    private javax.swing.JScrollPane rolagemTabela;
    private javax.swing.JScrollPane rolagemTabela2;
    private javax.swing.JScrollPane rolagemTexto;
    private javax.swing.JTable tabelaAprovador;
    // End of variables declaration//GEN-END:variables
}
